package events

import (
	"github.com/bububa/rakuten-go/advertisering/enum"
	"github.com/bububa/rakuten-go/advertisering/model"
)

type Transaction struct {
	// EtransactionID Transaction's unique ID
	EtransactionID string `json:"etransaction_id,omitempty"`
	// AdvertiserID Advertiser's ID
	AdvertiserID model.Uint64 `json:"advertiser_id,omitempty"`
	// SID Your Publisher ID
	SID model.Uint64 `json:"sid,omitempty"`
	// OrderID Advertiser's ID for the order
	OrderID string `json:"order_id,omitempty"`
	// OfferID Offer ID associated with the offer that the transaction was commissioned on
	OfferID string `json:"offer_id,omitempty"`
	// SkuNumber SKU for the item. Is blank if the Advertiser doesn't report it.
	SkuNumber string `json:"sku_number,omitempty"`
	// SaleAmount Amount the consumer paid for the item in the Order
	SaleAmount float64 `json:"sale_amount,omitempty"`
	// Quantity Quantity of the Items purchased
	Quantity int `json:"quantity,omitempty"`
	// Commissions Total base commission generated by this transaction
	Commissions float64 `json:"commissions,omitempty"`
	// ProcessDate Date and time when this transaction was processed by Rakuten. Format used is EEE MMM DD YYYY HH:mm:ss ZZZZ. Time zone is defaulted to GMC+0000 (UTC).
	ProcessDate model.DateTime `json:"process_date,omitzero"`
	// TransactionDate Date and time when the Order was placed on the Advertiser's site. Format used is EEE MMM DD YYYY HH:mm:ss ZZZZ. Time zone is defaulted to GMC+0000 (UTC).
	TransactionDate model.DateTime `json:"transaction_date,omitzero"`
	// TransactionType Identifies if the transaction is realtime or batch
	TransactionType enum.TransactionType `json:"transaction_type,omitempty"`
	// ProductName Name of the item purchased or returned. This is an optional field for the Advertiser; only available if the Advertiser reports it.
	ProductName string `json:"product_name,omitempty"`
	// U1 Identifies the click that the transaction originated from. This is an optional field for the Publisher; only available if the Publisher reports it.
	U1 string `json:"u1,omitempty"`
	// Currency Currency of the sale amount for the transaction
	Currency enum.Currency `json:"currency,omitempty"`
	// IsEvent Identifies if the reported entity is an Event or Transaction
	IsEvent model.Bool `json:"is_event,omitempty"`
	// CommissionsListID ID of the commission list the transaction belongs to. This is an optional field for the Advertiser; only available if the Advertiser reports it.
	CommissionsListID string `json:"commissions_list_id,omitempty"`
}
